apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-rollback
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cluster-rollback
  template:
    metadata:
      labels:
        app: cluster-rollback
    spec:
      serviceAccountName: cluster-rollback-sa
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "cluster_rollback.web.app"]
          ports:
            - containerPort: 8000 